version: '3'

silent: true

vars:
  PACKAGE_MANAGER: bunx
  VERSION:
    sh: npx -c 'echo $npm_package_version'

tasks:
  default:
    cmds:
      - echo "defalt-dashboard {{.VERSION}}"
  install:
    cmds:
      - |
        echo "Installing dependencies..."
        {{.PACKAGE_MANAGER}} install

  dev:
    cmds:
      - echo "Starting development server..."
      - |
        {{.PACKAGE_MANAGER}} umi dev

  build:
    env:
      NODE_ENV: production
      BABEL_CACHE: none
    cmds:
      - |
        {{.PACKAGE_MANAGER}} umi build

  tag:
    cmds:
      - cmd: |
          git tag -a v{{.VERSION}} -m "chore: Release v{{.VERSION}}"

  test:
    cmds:
      - echo "Testing..."

  deploy:
    cmds:
      - echo "Deploying to Netlify..."
      - netlify deploy --prod

  publish:
    cmds:
      - task: build
      - task: deploy
