version: '3'

silent: true

vars:
  PACKAGE_MANAGER: bun
  VERSION:
    sh: echo $(npx -c 'echo $npm_package_version')

tasks:
  install:
    cmds:
      - |
        echo "Installing dependencies..."
        npx npm-check-updates -u
        {{.PACKAGE_MANAGER}} install

  dev:
    cmds:
      - echo "Starting development server..."
      - npx umi dev

  build:
    env:
      NODE_ENV: production
      BABEL_CACHE: none
    cmds:
      - npx umi build

  tag:
    cmds:
      - cmd: |
          git tag -a v${VERSION} -m "chore: Release v${VERSION}"

  test:
    cmds:
      - echo "Testing..."

  deploy:
    cmds:
      - echo "Deploying to Netlify..."
      - netlify deploy --prod

  publish:
    cmds:
      - task: build
      - task: deploy
