name: SonarQube Report

on:
  workflow_dispatch:

jobs:
  scan:
    name: Run Scanner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: anyscripts/run-sonar-scanner@main
        id: run-sonar-scanner
        with:
          SONAR_URL: ${{ secrets.SONAR_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_QUALITY_GATE: 'Skitsanos'


      - run: |
          echo "Testing"
#      - uses: skitsanosinc/sonarqube-issues-report@v1.0.0
#        id: report-generator
#        with:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
#          SONAR_PROJECT: default-dashboard
#
#      - run: |
#          echo "output: ${{ steps.report-generator.outputs.PREVIEW_URL }}"