name: SonarQube Report

on:
  workflow_dispatch:

jobs:
  scan:
    name: Generate Report
    runs-on: ubuntu-latest
    steps:
      - uses: anyscripts/run-sonar-scanner@main
        id: run-sonar-scanner

      - run: |
          echo "Testing"
#      - uses: skitsanosinc/sonarqube-issues-report@v1.0.0
#        id: report-generator
#        with:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
#          SONAR_PROJECT: default-dashboard
#
#      - run: |
#          echo "output: ${{ steps.report-generator.outputs.PREVIEW_URL }}"